services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_9CVrka4dxJbA@ep-late-field-ap8y6gee-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - PORT=3000

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000